logging:
  level:
      com:
          study:
              full:
                  stack:
                      fullstack_project:
                          controller: trace
      org:
          hibernate: info

test:
  db: localdb

spring:
  profiles:
    active: local #기본 환경 선택
# local 환경
---
mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
  profiles: local
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
  flyway:
      enabled: false
  h2:
      console:
          enabled: true
  jpa:
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: false
      hibernate:
          ddl-auto: create
      show-sql: true
server:
  port: 8080
env:
  servers:
    - dev.example.com
    - prod.example.com

# 운영환경
---
spring:
  profiles: prod
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      tomcat:
        connection-properties: useUnicode=yes;characterEncoding=UTF-8;autoReconnection=true
        init-s-q-l: select 1
        test-on-borrow: true
        test-while-idle: true
        validation-query: select 1
        time-between-eviction-runs-millis: 600000
  flyway:
      enabled: false
  h2:
      console:
          enabled: true
  jpa:
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: false
      hibernate:
          ddl-auto: create
      show-sql: true
server:
  port: 8081